### ISSUE TITLE
Add scrapeDate column to data

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#179]
This has been requested a few times, and it seems to be required now that we might release data with stale timeseries data...

**Comment by feliperoberto** [comment]
I saw https://github.com/lazd/coronadatascraper/commit/efc561e6d23b054f33b41ce8c67ac904983a1628 , what still should be done?

**Comment by jzohrab** [comment]
Spec notes from slack conversation with lazd:

We should add a "scrapeDate" field (name TBD) to `dist.json` giving the date of the cache file that was used for the scrape.  e.g.

```
{
    "state": "PA",
    "country": "USA",
    "aggregate": "county",
    ...
    "population": 102811,
    "scrapeDate": blah  <<<<<<<<<<<<<<
  },
``` 

slack convo notes:

```
Larry Davis: it should be the datetime of the cache file being used
jz: right.  of the folder it’s in?
Larry Davis: oh the file itself, really… but even then that modified date is probably wrong
jz: my cache has folders 2020-3-27 etc.  Is that the same in prod?
Larry D: should be
```

**Comment by hyperknot** [comment]
I don't know where to put it in a timeseries CSV, probably nowhere. But in a timeseries JSON it'd be a nice bonus.

And it really should be a scrape time in local timezone, not scrape date.

To make this project really high quality, it should run every hour, and keep the latest time for each day. So for example, it'd scrape at 20:50, 21:50, 22:50, 23:50 local time and then keep the number of the 23:50 one. scrape_time would be then saved as `2020-03-30T23:50:00+02:00`

@HerbCaudill

**Comment by hyperknot** [comment]
@ryanblock

**Comment by hyperknot** [comment]
@camjc

**Comment by hyperknot** [comment]
But I totally agree about logic behind it, it should be the datetime of the cache file used to compute the values.

**Comment by chunder** [comment]
It should *not* be in a local timezone. Recording of the time of events should be in UTC. You can translate that to any timezone for display purposes if desired.

**Comment by chunder** [comment]
I am also interested in adding an `updatedAt` field to the records returned by scrapers. Many data sources explicitly note `Last updated at XXXX`.

@lazd and I have been talking about having scrapers throw errors if they're scraping data which hasn't been updated in more than 1 day. That likely means they are scraping a source which is no longer being updated. Agencies often switch to a new web page or csv file or somesuch and just leave the old page/file hanging around with stale data in it.

**Comment by hyperknot** [comment]
The problem is that UTC times will confuse most users. For example it might seem like we've been scraping in the future.

A local time with timezone information in ISO date contains both the local time, and the UTC one, like `2020-03-30T18:26:20+02:00`

**Comment by jzohrab** [comment]
I proposed a different take on slack, which was just to modify the writing of the output `dist.json`, and not actually changing the the data structures returned by the scrapers.

To use the date of the cache file, each call to `get` would have to return two things: 

```
{
  bodyContent: [ the string of the HTML/etc from the url or the cached file],
  cacheDate: date of the cache file that was used for the data
}
```

This would require changing all of the scrapers.  Not a huge deal, but it's thrash.

*However,* since every scraper only uses `date = process.env.SCRAPE_DATE || datetime.getYYYYMD()` for the cache lookup, and `null` for timeseries, then we can just add `location.scrapeDate = process.env.SCRAPE_DATE || datetime.getYYYYMD()` to each location when we call `src/events/processor/write-data/index.js` `writeData`:

```
  // Add scrape date.
  const scrapeDate = process.env.SCRAPE_DATE || datetime.getYYYYMD();
  const outlocs = locations.map(loc => {
    loc.scrapeDate = scrapeDate;
    return loc;
  });

  await fs.writeFile(path.join('dist', `data${suffix}.json`), JSON.stringify(outlocs, null, 2));
```

This yields `data.json`:

```
[
  {
    "state": "PA",
    "country": "USA",
... [SNIP] ...
    "population": 102811,
    "scrapeDate": "2020-3-30"
  },
```

I feel I'm missing something!

**Comment by hyperknot** [comment]
I think this could wait until we change the cache structure (if we ever do that). For example 
```
{
  bodyContent: [ the string of the HTML/etc from the url or the cached file],
  cacheDate: date of the cache file that was used for the data
}
```

This wouldn't really work on a PDF, unless we go really crazy and encode the PDF as base64. Also, hourly scraping might not work with the current GitHub based cache, there might be just way too many files.

**Comment by jzohrab** [comment]
Closing this issue as I don't believe it's applicable with Li.

* "seems to be required now that we might release data with stale timeseries" - in Li we can and should explicitly specify the date of data, if the data itself has date, rather than assuming it's an arbitrary value.
* we shouldn't assume the "latest" data is "current", we should just specify the date.
* we currently crawl multiple times per day
* we have "updated" in the case-data table, but aren't including it on any report, yet.
