### ISSUE TITLE
Last acquired timestamp as text file

### ISSUE THREAD

**Issue by DavidGeeraerts** [covidatlas/coronadatascraper#18]
Create a simple text file that provides a timestamp (in UTC format) as to when the last acquired run happened. Would be part of the metadata record. Convenient to have it as a separate file for easy program check.

**Comment by lazd** [comment]
This could be included as a field in the data instead of a separate textfile.

**Comment by jzohrab** [comment]
Hi @DavidGeeraerts , for acquired run, do you mean the date that the source data was cached?  If yes, Ryan B is working on a new caching system that will have that information readily available as part of the filename.

**Comment by DavidGeeraerts** [comment]
@jzohrab Seems this is now going to be handled with `publishedDate`  &  `collectionDate`
`publishedDate` when the authority last published/updated the records
`collectionDate` when the scraper copied the records

**Comment by jzohrab** [comment]
Thanks, will keep an eye on this and resolve if/when the change is released.  If not, will get back to you, as this sort of data is useful.  Thanks DG.

**Comment by jzohrab** [comment]
Closing this for now.  We haven't had a request for this since this issue was opened.  The data is available, _somewhat_.  The source files have datetime stamp in the filename, and the Li casedata table 'updated' field has the date the scrape occurred.  We _don't_ have a clear mapping of data point to file, eg "this 'cases' count of 42 was pulled from file 2020-08-22.json which was from URl xyz, and was scraped on date abc using scraper sss".
