### ISSUE TITLE
Refactor to separate concerns between crawling/scraping and data processing

### ISSUE THREAD

**Issue by ryanblock** [covidatlas/coronadatascraper#295]
In order to facilitate the move to production infra and a more resilient app architecture, we're going to separate out crawling + scraping from post-processing.

Given the following, please also assume the application must continue to run is!

For the purposes of this exercise, let's assume the following folders:
- `src/events/crawler`
  - responsible for everything related to fetching and scraping sources
  - responsible for storing cache data to disk (and soon S3)
- `src/events/processor`
  - responsible for validating, deduping, etc. data
  - responsible for geojson tagging, population metadata, etc.
  - responsible for storing processed data sets (to S3, database, etc.)

Assumptions and considerations:
- `crawler` can invoke and pass state unidirectionally to `processor` (via reasonably sized JSON payloads or S3)
- `crawler` has its own set of dependencies independent of those of `processor`
- Both `crawler` and `processor` can share code; any code to be shared between those two (and any other functions) should be placed within `src/shared`
- Invocations will have as much as 3GB of memory, and 15 minutes of execution time before timeout

Additional future considerations:
- `crawler` will eventually fetch and run a single scraper upon each invocation; this doesn't have to be the first version, however
- ___your considerations here!___

**Comment by lazd** [comment]
This is 100% how this should work, and we're already halfway there with the refactoring work @qgolsteyn has done.

**Comment by qgolsteyn** [comment]
Quick round of questions @ryanblock:

- Would we need to add a `package.json` for each folder? Essentially, do we need to move to a monorepo structure, where each folder manages its dependencies.
- How would the data be transfered between concerns? Would they be run as part of the same script? Or do we need to save some intermediate data to the disk?

**Comment by ryanblock** [comment]
> Would we need to add a package.json for each folder?

We will eventually do this, yes, and Architect will manage those subtree dependencies for us. (For now, package at root containing these deps are fine!)

> How would the data be transfered between concerns? Would they be run as part of the same script? Or do we need to save some intermediate data to the disk?

You can have one function call another with whatever JSON-convertible object you like – we will eventually transform those local function calls into cloud function event invocations with the same payload (JSON encoded).

**Comment by ryanblock** [comment]
Having slept on this and given more thought today to some edges, wanted to add a few points:

- Feel free to wing it with the dirs/naming under `src/events/` and exactly how you separate things, I just want to make sure this isn't being overly prescriptive!
  - The purpose of the examples above was just to help ensure that the crawler stays within reasonable code payload boundaries; for example, if you wanted to break up crawler even further that's feasible too
- However, one thing I am fairly certain that needs to happen is that scrapers will need to be in `src/shared` (e.g. `src/shared/scrapers`) – this is because multiple functions will need access to the scrapers in order to operate on them
- A major 🔑 when working through this: imagine each function invocation is only responsible for a data source at a given time (e.g. we aren't going to act on large datasets, just one at a time through the data pipeline)

**Comment by ryanblock** [comment]
Per conversation with @qgolsteyn this evening, will be cutting a branch tonight or tomorrow get this going with collab from (hopefully) @lazd + @brianleroux!

**Comment by jzohrab** [comment]
Reading the above and thinking about the problem after some discussions with Ryan B, I sketched out some code in a simple branch to think through it.  This branch is throwaway, but some of the ideas in it should be useful.

The branch: https://github.com/jzohrab/coronadatascraper/tree/poc-split-crawling-and-parsing

A comparison of the code to upstream/master: https://github.com/covidatlas/coronadatascraper/compare/master...jzohrab:poc-split-crawling-and-parsing

Points:

* Clear separation between crawling and scraping.
* Added a “scraperType” field to scrapers to let us gradually migrate scrapers over.  Existing code would still work, and updated scrapers would use the new code path.  When all scrapers have been migrated, we could delete the old code paths.  Migrating would ideally happen as fast as possible!
* Scraping only hits the cache … and actually, for each scraper, the “run scraping” routine gets the latest data set from the cache for that scraper type, and then determines which scraper should actually process the data. So that would provide a “fall back” mechanism, if the cached data is missing for a given date.  Essentially, scraping would never fail, because CI would run every scraper for every cache date.

In my mind, this all works pretty easily. :-)  The scrapers and crawlers themselves are quite easily testable.  We could also include simple dependency injections for the scrapers to use fake caches, missing caches, etc.

**Comment by ryanblock** [comment]
Closing in favor of https://github.com/covidatlas/coronadatascraper/issues/782
