### ISSUE TITLE
Replace hand-rolled date functions with moment.js or similar

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#42]
They're getting pretty gross. Let's use a library.

**Comment by SteveWallace** [comment]
Do you want to just re factor the datetime.js to use moment or would you rather remove that helper and just use moment where we need it? Less change and probably better encapsulation with the former probably.

**Comment by qgolsteyn** [comment]
See #50. We still need to update the codebase with the new `datetime.js` before the PR can be merged.

**Comment by HerbCaudill** [comment]
Moment & Luxon etc. are great for what they do, but **they don't solve the problem we're having here**, which is that most of the time we don't care at all about times or time zones and we just need to work with stripped-down dates. 

I've been down this exact road before (hand-rolled date functions -> moment.js -> js-joda) with [my company's product](devresults.com). The happy place we ended up at was to eliminate the use of the native JS Date object throughout the codebase, and to use the appropriate js-joda classes instead as appropriate:

- [LocalDate](http://js-joda.github.io/js-joda/manual/LocalDate.html) for when you only care about calendar date, not time or time zone 👈 **99% of this project's use cases**
- [LocalTime](http://js-joda.github.io/js-joda/manual/LocalTime.html) for when you only care about time of day, not date, and not in any particular time zone
- [LocalDateTime](http://js-joda.github.io/js-joda/manual/LocalDateTime.html) for when you care about time of day + calendar date, but not time zone
- [ZonedDateTime](http://js-joda.github.io/js-joda/manual/ZonedDateTime.html) for when you care about time of day + calendar date in a specific time zone

Mixing these 4 very different combinations of concerns in a single object is a recipe for heartache and despair. 

js-joda is fast, solid and battle-tested: It replicates the API of [joda-time](https://github.com/JodaOrg/joda-time), which is the gold standard in the Java world, and replicates its test suite (1700+ tests). 

@lazd I can do this work tomorrow (Sunday, CET) if you give me the green light.

**Comment by hyperknot** [comment]
@HerbCaudill we definitely need to care about timezones throughout this project. Soon timezones will be everywhere. We will run scrapers say hourly, and then want to transform the acquisition time to local time for every locale we are working with.

We definitely need a reliable and tested date library which handles timezones perfectly.

**Comment by HerbCaudill** [comment]
@hyperknot For those cases, then, you can use joda's ZonedDateTime, which works beautifully. 

The value of the date field in a timeseries is what's responsible for most of the messiness we're dealing with; that's always going to be just a date, because no one is actually reporting at a finer temporal resolution that that. 

With Moment.js, Luxon, etc. there's fundamentally no way of getting away from having a time and a time zone associated with a date. You can set that to 0:00:00 and UTC all you want, but then you're always going to have to worry about that getting converted to someone else's time zone. In some situations it does, in others it doesn't! And when it gets converted and the runtime is east of Greenwich, then you're working with the day _after_ your date. I'm telling you that there is nothing but darkness down that road.

**Comment by hyperknot** [comment]
I'm not sure I understand. Let's say we implement hourly scraping, and then we want to reconstruct the latest daily values from this. So we'd have a scrape_time in UTC in a database or S3 for example.

Now we want to convert this to local time, to know which day was it in. How would you do that in joda?

Also, does it support fromISO(), toISO() and toISODate() like methods?

**Comment by HerbCaudill** [comment]
In that case you would timestamp the scrapes with a ZonedDateTime, which is explicitly designed for that purpose.

**Comment by HerbCaudill** [comment]
> Also, does it support fromISO(), toISO() and toISODate() like methods?

Yes

**Comment by hyperknot** [comment]
OK, I've checked those methods and all seem to be supported. If in your opinion js-joda-timezone is production ready, I'm happy to recommend using this throughout this project.

BTW, scrape time will soon be ISO date, so your logic could be simplified in the future.

**Comment by HerbCaudill** [comment]
More on Moment's inability to represent a date without a time or vice versa:

https://github.com/moment/moment/issues/3455

**Comment by hyperknot** [comment]
OK, I'm happy to support js-joda, especially if @HerbCaudill helps us in some initial problems we might encounter.

**Comment by ryanblock** [comment]
Would like to advocate for [`spacetime`](https://github.com/spencermountain/spacetime) (cc @spencermountain!) but anything that's relatively lightweight should get the job done. It just needs to be able to re-cast a time + IANA tz string to a normalized date stamp (specifically `YYYY-MM-DD`)

Here's the impl from my previous prototype that I showed earlier today:
- https://github.com/covidatlas/covidatlas/blob/master/src/shared/utils/get-date.js which accepts the tz string from:
- https://github.com/covidatlas/covidatlas/blob/master/src/events/tracker/visitors/us/ca/san-francisco/index.js#L2

**Comment by hyperknot** [comment]
@ryanblock the code you linked to is the definition of hand-rolled time formatting code.

The point of Luxon is that they have super reliable and well tested tested `fromISO()`, `toISODate()` and `toISO()` methods. joda seems to have the same functions.

**Comment by HerbCaudill** [comment]
here's what that looks like in js-joda FWIW: 

```js
const currentDateTimeAt = tz => ZonedDateTime.now(ZoneId.of(tz)).toString()

console.log(new Date()) // 2020-03-22T18:03:23.750Z
console.log(currentDateTimeAt('America/Chicago')) // 2020-03-22T13:00:24.365-05:00[America/Chicago]
```

**Comment by ryanblock** [comment]
@hyperknot I mean, I guess? Pretty straightforward impl but sure, we can actually reduce even that example quite a bit (I forgot there were some methods in there that weren't documented). Like so:
```
let spacetime = require('spacetime')
let s = spacetime(Date.now(), 'America/Los_Angeles')
s.format()      // 2020-03-24
s.format('iso') // 2020-03-24T19:57:02.376-07:00
```
Production installs:
- `spacetime`: 499KB
- `js-joda`: 4.1MB

Whatever we choose, the thing that outputs locale aware strings of `2020-03-24` + `2020-03-24T19:57:02.376-07:00` should certainly be nothing more than a minor impl detail.

How are we feeling otherwise about progress in knocking this out and getting dates normalized?

**Comment by ryanblock** [comment]
@hyperknot I mean, I suppose? Isn't the primary concern getting the correct locale datestamp, and not string formatting? In any event, I forgot that there were some better methods for accessing those formats:
```
let spacetime = require('spacetime')
let s = spacetime(Date.now(), 'America/Los_Angeles')
s.format()      // 2020-03-24
s.format('iso') // 2020-03-24T19:57:02.376-07:00
```
Otherwise, production size just fwiw:
- Spacetime: 499KB
- js-joda: 4.1MB

@HerbCaudill can make the call on what we use to get locale-cast `2020-03-24` + `2020-03-24T19:57:02.376-07:00`. Anything we can do to help move forward, Herb?

**Comment by HerbCaudill** [comment]
see #393

**Comment by ryanblock** [comment]
PR merged; we still have a lot of handrolled date functions, although I'm not certain they were avoidable without rewriting a lot of this codebase.

👏 @HerbCaudill!
