### ISSUE TITLE
Tuolumne County, CA scraper on wrong page

### ISSUE THREAD

**Issue by dotysan** [covidatlas/coronadatascraper#444]
It's using https://www.tuolumnecounty.ca.gov/CivicAlerts.aspx?AID=605 which still reports zero cases. But it should be using https://www.tuolumnecounty.ca.gov/250/Public-Health which reports one case since yesterday morning.

**Comment by lazd** [comment]
@HarrietRowan can you investigate?

**Comment by HarrietRowan** [comment]
I am actually not counting that as a case, since it is an out of-county resident who was brought to a facility in Tuolomne and is likely being counted in another county's numbers, although I haven't had time to confirm that. But re: which page to scrape, this is the correct one: https://www.tuolumnecounty.ca.gov/250/Public-Health

**Comment by dotysan** [comment]
> I am actually not counting that as a case, since it is an out of-county resident who was brought to a facility in Tuolomne and is likely being counted in another county's numbers, although I haven't had time to confirm that.

Yes, you are correct. As long as we include it in Mono County. Although it raises the interesting question of collecting separate data on location of infection and current location of the infected...

**Comment by dotysan** [comment]
I've added comment to source list https://docs.google.com/spreadsheets/d/1T2cSvWvUvurnOuNFj2AMPGLpuR2yVs3-jdd_urfWU4c/edit?disco=AAAAGWtQdH0 and am working on a scraper for both Mono and TuoCo.

**Comment by jzohrab** [comment]
Closing, I believe this issue is stale.
