### ISSUE TITLE
Add timeseries-multivalent.json with all sources represented

### ISSUE THREAD

**Issue by lazd** [covidatlas/coronadatascraper#586]
COVIDActNow requires data from all sources to do their own cross-checking and running of models against different data sources. We're already solving the normalization issue for all data sources and count provide them with a single file with all the data they need.

`timeseries-multivalent.json` - a single object keyed on the location name like [`timeseries-byLocation.json`](https://coronadatascraper.com/#timeseries-byLocation.json), with FIPS codes for all the things, and data from source we have represented:

i.e.:

```
{
 "Victoria, AUS": {
    "dates": {
      "2020-3-31": {
        "cases": {
          "Victoria Government": 968,
          "Austrailian Government": 968,
          "JHU": 917
        },
        "deaths": {
          "JHU": 4
        }
      }
    },
    "country": "AUS",
    "state": "Victoria",
    "coordinates": [
      145.4695804428331,
      -36.537788791607284
    ],
    "tz": [
      "Australia/Melbourne"
    ],
    "population": 6594804
  }
}
```

The names of the keys under `cases`/`deaths` will have to shake out somehow, we may need unique IDs for each datasource or something, but this is close.

**Comment by jzohrab** [comment]
This is implemented -- with a different output model -- in https://github.com/covidatlas/li/blob/master/docs/reports.md.  I believe it is sufficient at the moment.  We could get more granular with the attribution if sources no longer did things like join different data sources together, but that's a different story.  Please open an issue in Li if you feel that the implementation is insufficient; otherwise, I think we have it covered.  Cheers! jz
