### ISSUE TITLE
No data for states of India staring 3/31

### ISSUE THREAD

**Issue by anuragsodhi** [covidatlas/coronadatascraper#654]
## Snippet/screenshot
```
<!-- If you can, please include a snippet of the file here, or a screenshot, to help us find it.-->
```

**Comment by pankaj-giri** [comment]
Can consider scraping - https://www.covid19india.org/ where the information about every state is updated every few hours

**Comment by lazd** [comment]
Fixed in the latest data. Please re-open if there is an issue.

https://github.com/covidatlas/coronadatascraper/issues/686 We're still missing GeoJSON for:

  ❌ Could not find location Ladakh, iso1:IN
  ❌ Could not find location Telengana, iso1:IN

https://github.com/covidatlas/coronadatascraper/issues/687 Missing population data for:

  ❌ Arunachal Pradesh, iso1:IN: ?
  ❌ Assam, iso1:IN: ?
  ❌ Jharkhand, iso1:IN: ?
