### ISSUE TITLE
All New York Counties are Missing

### ISSUE THREAD

**Issue by slezakbs** [covidatlas/coronadatascraper#658]
## Location, date, and short issue description
NY, USA has changed where they are posting cases by Borough.

## Source
old_location: https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary.pdf
new location: https://raw.githubusercontent.com/nychealth/coronavirus-data/master/boro.csv

**Comment by slezakbs** [comment]
The format of the NY County page has changed as well

**Comment by lazd** [comment]
This is fixed in the latest data. Please take a look and re-open if there is an issue.

![image](https://user-images.githubusercontent.com/201344/78532812-b98f4800-779c-11ea-812f-c9c7c84e12f4.png)
![image](https://user-images.githubusercontent.com/201344/78532931-e8a5b980-779c-11ea-8ee6-6a6a19197f9f.png)
