### ISSUE TITLE
CA-USA counts did not update on April 19

### ISSUE THREAD

**Issue by tautme** [covidatlas/coronadatascraper#862]
CA-USA counts did not update on April 19
April 19 counts are same as April 18 counts
also April 10 - 11

## Source
in data.csv and timeseries.csv and timeseries_jhu.csv
state level and county level

## File
I checked at random some CA counties, but assume all are not updated.

## Issue details
expect numbers to increase

## Snippet/screenshot
![image](https://user-images.githubusercontent.com/15580867/79823833-41a74d00-835a-11ea-9aa5-2e9528681dee.png)

**Comment by lazd** [comment]
@HarrietRowan I suppose this is due to the new file format? We haven't implemented it yet.

**Comment by HarrietRowan** [comment]
I didn't actually change the format yet, but I did start pasting over fewer columns, but I purposefully didn't change those column headers because I thought that would keep it from breaking. I still plan on changing to a different data schema in the next few days, but will send it to you beforehand and it's mostly the same but with a few more columns. The current version are just a condensed version of what I had been doing up until friday.

**Comment by lazd** [comment]
Ok @HarrietRowan, I'll investigate. Thanks!
