### ISSUE TITLE
Data not updated

### ISSUE THREAD

**Issue by tlampe0615** [covidatlas/coronadatascraper#956]
Last update was on 05/02/2020

**Comment by tlampe0615** [comment]
Looks like same issue from 04/20?  Please advise

**Comment by jzohrab** [comment]
Hello @tlampe0615.  I just checked the site at https://coronadatascraper.com/#data.csv and see some recent data.  What data are you checking?  Thanks for the message! jz

**Comment by tlampe0615** [comment]
When we checked the data at 6:30 AM ET, and again 8:30AM ET, the data only refelcted through 05/02/2020.  Just checked again, and looks like there is 05/03/2020 data.  When are you publishing previous days data?  Has the schedule changed?  Previously we could pull previous day 6:30AM ET?

**Comment by lazd** [comment]
The schedule has not changed -- we're publishing a day's data at around 10PM that day. Data was definitely scraped and published last night, BUT I'm seeing that the commit didn't show up until 1 hour ago: https://github.com/covidatlas/coronadatascraper/commits/gh-pages

That's very odd, because I still have the terminal window up from the server last night and I see it was done on time. Perhaps there was a GitHub issue. In any case, data is up now. I'll double check tonight's deployment on GitHub pages to make sure it goes out promptly.

Thanks!
