### ISSUE TITLE
NC County Data Error

### ISSUE THREAD

**Issue by pkaplan2524** [covidatlas/coronadatascraper#960]
For the US State of North Carolina county data timeline (via timeseries-byLocation.json) it looks like May 2nd and 3rd are using identical data. This is inaccurate.

**Comment by pkaplan2524** [comment]
Correction: May 1st and 2nd are using identical data.

**Comment by lazd** [comment]
Cannot verify this: https://staging.covidatlas.com/jones-county-north-carolina-united-states

Please re-open if you can verify.

**Comment by lazd** [comment]
Ok, I see May 1st and 2nd seem to be identical.

**Comment by lazd** [comment]
Just refreshed the data and still seeing 1st and 2nd as identical.

Source data is identical:

May 1st: https://github.com/lazd/coronadatascraper-cache/blob/master/2020-5-1/cf91be8fb40e473d8ff941f6dd1a8a88.csv

May 2nd: https://github.com/lazd/coronadatascraper-cache/blob/master/2020-5-2/cf91be8fb40e473d8ff941f6dd1a8a88.csv

It's possible they didn't update data in that CSV on the 2nd because it was Saturday.

However, the other North Carolina pages do have updates:

May 1st: https://web.archive.org/web/20200501203909/https://www.ncdhhs.gov/divisions/public-health/covid19/covid-19-nc-case-count#by-counties

May 2nd: https://web.archive.org/web/20200502190520/https://www.ncdhhs.gov/divisions/public-health/covid19/covid-19-nc-case-count#by-counties

@pkaplan2524 to fix this, go ahead and:

1. Make the current scraper a separate function
2. Extract the data for May 2nd from the link above as a JS array
3. Add a scraper that returns the array for `2020-5-2`
4. Add a scraper for `2020-5-3` that uses the separate function
